spring.application.name=user-service

# JDBC URL conntect to PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/AppClass

# Username and password of PostgreSQL
spring.datasource.username=postgres
spring.datasource.password=root

# Driver class name (PostgreSQL)
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (Hibernate) configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Encoding (xu ly tot voi tieng viet)
spring.datasource.hikari.connection-init-sql=SET NAMES 'UTF8'
