spring.application.name=user-service

# port user-service (management-service ?ang g?i http://localhost:8081)
server.port=8081

# JDBC URL connect to MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/AppClass
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.datasource.hikari.connection-init-sql=SET NAMES 'UTF8'

api.prefix=/api
