spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates=Path=/api/users/**

spring.cloud.gateway.routes[1].id=management-service
spring.cloud.gateway.routes[1].uri=lb://management-service
spring.cloud.gateway.routes[1].predicates=Path=/api/management/**

eureka.client.service-url.default-zone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.lease-renewal-interval-in-seconds=30
